version: "3"
services:

  database:
    image: mysql:5.6
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: myrootpassword
      MYSQL_DATABASE: crudgames
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    expose:
      - "3306"
    volumes:
      - ./database:/var/lib/mysql
    networks:
      - mynetwork

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.9
    platform: linux/amd64
    ports:
      - "8081:80"
    networks:
      - mynetwork
    environment:
      PMA_HOST: database
      PMA_USER: test
      PMA_PASSWORD: test

  node:
    build:
      context: ./backend
      dockerfile: Dockerfile.node
    environment:
      DB_HOST: database
      DB_USER: test
      DB_PASSWORD: test
      DB_NAME: crudgames
    depends_on:
      - database
    ports:
      - "3000"
    restart: always
    networks:
      - mynetwork

  nginx:
    build:
      context: ./frontend
      dockerfile: Dockerfile.nginx
    environment:
      REACT_APP_BACKEND_URL: http://node:3001
    ports:
      - "80:80"
    networks:
      - mynetwork
    depends_on:
      - node

networks:
  mynetwork:
    driver: bridge

volumes:
  mysql-data:
  my-nodejs-app:


